version: '2'
services:

  web:
    image: node:6.1
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app/app
    command: sh -c 'npm install; npm install -g nodemon ; nodemon index.js & npm run gulp'
    ports:
      - "3003:3003"
    depends_on:
      - mongo
    networks:
      - all
    environment:
      MONGODB_URI: "mongodb://mongo:27017/"

  mongo:
    image: mongo:3
    command: mongod --smallfiles
    networks:
      - all

networks:
    all:
